apiVersion: apps/v1
kind: Deployment
metadata:
  name: pypiserver
  namespace: pypi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pypiserver
  template:
    metadata:
      labels:
        app: pypiserver
    spec:
      containers:
      - name: pypiserver
        image: docker-registry.mw/pypiserver:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: PYPISERVER_PASSWORDS
          value: "admin:adminpass,user:userpass"
        volumeMounts:
        - name: pypiserver-storage
          mountPath: /data/packages
      volumes:
        - name: pypiserver-storage
          persistentVolumeClaim:
            claimName: pypi-storage-pvc

