apiVersion: v1
kind: PersistentVolume
metadata:
  name: pypi-storage-pv
spec:
  capacity:
    storage: 5Gi  # Adjust the storage size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /mnt/ext1/pypi
    server: 192.168.0.11

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pypi-storage-pvc
  namespace: pypi
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage


