apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-cloner
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  entrypoint: cloner
  arguments:
    parameters:
      - name: giturl
        value: https://github.com/MatiWall/  # Provide the correct GitHub URL here
      - name: revision
        value: HEAD
      - name: branch
        value: main
      - name: path
        value: extensions-opentelemetry
  templates:
    - name: cloner
      inputs:
        parameters:
          - name: giturl
            value: "{{workflow.parameters.giturl}}"
          - name: revision
            value: "{{workflow.parameters.revision}}"
          - name: branch
            value: "{{workflow.parameters.branch}}"
          - name: path
            value: "{{workflow.parameters.path}}"
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - git clone {{inputs.parameters.giturl}}{{inputs.parameters.path}} --branch {{inputs.parameters.branch}}
