# my-react-app/values.yaml


cronjob:
  global:
    environment: Test
    system: Testing
    application: otel-test
    deployable_unit: test

  schedule: "*/2 * * * *"
  suspend: true
  image:
    repository: docker-registry.mw/otel-test
    tag: 0.0.2
    pullPolicy: IfNotPresent

