# my-react-app/values.yaml


deployment:
  replicaCount: 1
  image:
    repository: docker-registry.mw/personal-website
    tag: 0.0.3
    pullPolicy: IfNotPresent

  service:
    name: personal-website-service
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    path: /
    url: matiaswallenius.mw.local

