# my-react-app/values.yaml


deployment:
  replicaCount: 1
  image:
    repository: your-docker-repo/my-react-app
    tag: latest
    pullPolicy: IfNotPresent

  service:
    name: my-react-app
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    path: /

