global:
  system: catcode
  application: backend
  deployableUnit: dependencies
deployment:
  replicaCount: 1
  secrets:
    enabled: false
  image:
    repository: docker-registry.mw.local/catcode.backend.dependencies
    tag: 0.1.2
    pullPolicy: IfNotPresent
  service:
    name: catcode-dependencies-api
    type: ClusterIP
    port: 80
    targetPort: 8001
  ingress:
    enabled: true
    path: /api/dependencies/v1
    host: catcode.mw.local
  appconfig:
    backend_url: http://catcode.mw.local/api/core-api/v1
