apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage-pv
spec:
  capacity:
    storage: 5Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany  # Adjust the access mode based on your requirements
  nfs:
    path: /mnt/ext1/prometheus
    server: 192.168.0.11

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany  # Must match the access mode specified in the PV
  resources:
    requests:
      storage: 5Gi  # Adjust the storage size as needed

