apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres.mw
  namespace: postgres

spec:
  entryPoints:
    - postgres-service

  routes:
  - match: HostSNI(`*`)
    services:
    - name: postgres-service
      port: 80
