apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-ingress-route-tcp
  namespace: postgres
spec:
  entryPoints:
    - postgres

  routes:
  - match: HostSNI(`*`)
    services:
    - name: postgres-service
      port: 6432

