apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: postgres-ingress
  namespace: postgres
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`postgres.mw`)
    priority: 10
    services:
    - name: postgres-service
      port: 80

