# my-react-app/values.yaml


deployment:
  replicaCount: 1
  image:
    repository: docker-registry.mw/homelab-api-catcode
    tag: 0.0.1
    pullPolicy: IfNotPresent

  service:
    name: my-react-app
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    path: /
    url: catcode-api.com

