# grafana-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-cm
  namespace: grafana
data:
  datasources.yaml: |-
    {{ .Files.Get "./datasources.yaml" | nindent 2 }}
  grafana.ini: |-
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    
    [database]
    type = sqlite3
    host = localhost:3306
    name = grafana

    [analytics]
    check_for_updates = true
    
    [security]
    admin_user = admin
    admin_password = admin
    secret_key = SW2YcwTIb9zpOOhoPsMm
    
    [auth.anonymous]
    enabled = true
    
    [auth.basic]
    enabled = false
