apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: grafana
data:
  grafana.ini: |
    # grafana.ini

    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins

    [server]
    http_port = 3000
    domain = example.com

    [database]
    type = sqlite3
    host = 127.0.0.1:3306
    name = grafana
    user = root
    password =

    [users]
    # Admin user
    admin_user = admin
    admin_password = admin

    [auth]
    disable_login_form = true

    [auth.anonymous]
    # enable anonymous access 
    enabled = true

    org_name = HomeLab
    org_role = Editor
