# grafana-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-cm
  namespace: grafana
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.monitoring.svc.cluster.local:80
        isDefault: true
      - name: Postgres
        type: postgres
        url: postgres-service.postgres.svc.cluster.local:5432
        user: postgres
        secureJsonData:
          password: 'postgres'
        jsonData:
          database: Test
