apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-service
  namespace: grafana
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`grafana.mw.local`)
    priority: 10
    services:
    - name: grafana-service
      port: 80

