apiVersion: v2
name: argo-workflow
appVersion: "1.0"
description: "Argo workflow"
version: 1.1.0
type: application
dependencies:
  - name: argo-workflows
    version: 0.41.6
    repository: https://argoproj.github.io/argo-helm
    alias: deployment