# my-react-app/values.yaml
global:
  system: catcode
  application: backend
  deployableUnit: catdocs

deployment:
  replicaCount: 1

  secrets:
    enabled: false

  image:
    repository: docker-registry.mw/catcode-backend-catdocs
    tag: 0.0.1
    pullPolicy: IfNotPresent

  service:
    name: catcode-catdocs-api
    type: ClusterIP
    port: 80
    targetPort: 8002

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    path: /
    url: catcode.backend.catdocs.mw
  appconfig: {"backend_url": "http://catcode-api-service.catcode.svc.cluster.local"}

