apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: vault-initialization-
spec:
  entrypoint: init-vault
  templates:
    - name: init-vault
      container:
        image: hashicorp/vault:1.8.0
        command: ["/bin/sh", "-c"]
        args: 
          - |
            vault operator init -key-shares=1 -key-threshold=1 -format=json > /tmp/keys.json
            export VAULT_UNSEAL_KEY=$(cat /tmp/keys.json | jq -r ".unseal_keys_b64[]")
            export VAULT_ROOT_KEY=$(cat /tmp/keys.json | jq -r ".root_token")
      outputs:
        parameters:
          - name: VAULT_UNSEAL_KEY
            valueFrom:
              path: /tmp/keys.json
          - name: VAULT_ROOT_KEY
            valueFrom:
              path: /tmp/keys.json
