apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-crb
subjects:
- kind: ServiceAccount
  name: otel-collector-sa
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: otel-collector-cr
  apiGroup: rbac.authorization.k8s.io
