apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      #serviceAccountName: otel-collector-sa
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        args:
          - "--config=/etc/otel/otel-collector-config.yaml"
        ports:
          - name: http
            containerPort: 4317
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otel
      volumes:
      - name: config-volume
        configMap:
          name: otel-collector-config

