apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      batch:

    exporters:
      elasticsearch:
        endpoint: "http://elasticsearch:9200"
        index: "otel-logs"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch]
---
