apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      batch:

    exporters:
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"

      otlphttp:
        endpoint: "http://tempo:3100"

      prometheus:
        endpoint: "prometheus:9090"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]
