apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      batch:
      k8sattributes:
        passthrough: true

    exporters:
      loki:
        endpoint: "http://loki-service.monitoring.svc.cluster.local:80/loki/api/v1/push"

      otlp:
        endpoint: "tempo-service.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors:
            - k8sattributes
            - batch
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors:
            - k8sattributes
            - batch
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors:
            - k8sattributes
            - batch
          exporters: [loki]
