apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-pipline
spec:
  entrypoint: build-and-deploy
  serviceAccountName: argo-workflow-svc
  volumeClaimTemplates:                 # define volume, same syntax as k8s Pod spec
    - metadata:
        name: workdir                     # name of volume claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

  arguments:
    parameters:
      - name: giturl
        value: https://github.com/MatiWall/  # Provide the correct GitHub URL here
      - name: revision
        value: HEAD
      - name: branch
        value: main
      - name: path
        value: extensions-opentelemetry
      - name: registry
        value: docker-registry.mw.local/
      - name: base-image
        value: python:3.12-1
      
  templates:
    - name: build-and-deploy
      steps:
        - - name: clone-repo
            template: cloner
            arguments:
              parameters:
                - name: giturl
                  value: "{{workflow.parameters.giturl}}"
                - name: revision
                  value: "{{workflow.parameters.revision}}"
                - name: branch
                  value: "{{workflow.parameters.branch}}"
                - name: path
                  value: "{{workflow.parameters.path}}"
        - - name: install-dependencies
            template: install-dependencies
            arguments:
              parameters:
                - name: registry
                  value: "{{workflow.parameters.registry}}"
                - name: base-image
                  value: "{{workflow.parameters.base-image}}"
        - - name: run-pytest
            template: run-pytest
            arguments:
              parameters:
                - name: registry
                  value: "{{workflow.parameters.registry}}"
                - name: base-image
                  value: "{{workflow.parameters.base-image}}"
          - name: run-mypy
            template: run-mypy
            arguments:
              parameters:
                - name: registry
                  value: "{{workflow.parameters.registry}}"
                - name: base-image
                  value: "{{workflow.parameters.base-image}}"
        - - name: build-package
            template: build-package
            arguments:
              parameters:
                - name: registry
                  value: "{{workflow.parameters.registry}}"
                - name: base-image
                  value: "{{workflow.parameters.base-image}}"
        - - name: push-package
            template: push-package
            arguments:
              parameters:
                - name: registry
                  value: "{{workflow.parameters.registry}}"
                - name: base-image
                  value: "{{workflow.parameters.base-image}}"

               
    - name: cloner
      inputs:
        parameters:
          - name: giturl
          - name: revision
          - name: branch
          - name: path
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - git clone {{inputs.parameters.giturl}}{{inputs.parameters.path}} --branch {{inputs.parameters.branch}}
        workingDir: /src
        volumeMount:
          - name: workdir
            path: src/
    - name: install-dependencies
      inputs:
        parameters:
          - name: registry
          - name: base-image
      container:
        image: "{{inputs.parameters.registry}}{{inputs.parameters.base-image}}"
        command: [sh, -c]
        args:
          - |
            ls
            poetry install --dev --local
        workingDir: /src/{{workflow.parameters.path}}
        volumeMount:
          - name: workdir
            path: /src
    - name: run-pytest
      inputs:
        parameters:
          - name: registry
          - name: base-image
      container:
        image: "{{inputs.parameters.registry}}{{inputs.parameters.base-image}}"
        command: [sh, -c]
        args:
          - poetry run pytest .
        workingDir: /src/{{workflow.parameters.path}}
        volumeMount:
          - name: workdir
            path: src/
    - name: run-mypy
      inputs:
        parameters:
          - name: registry
          - name: base-image
      container:
        image: "{{inputs.parameters.registry}}{{inputs.parameters.base-image}}"
        command: [sh, -c]
        args:
          - poetry run mypy .
        workingDir: /src/{{workflow.parameters.path}}
        volumeMount:
          - name: workdir
            path: src/
    - name: build-package
      inputs:
        parameters:
          - name: registry
          - name: base-image
      container:
        image: "{{inputs.parameters.registry}}{{inputs.parameters.base-image}}"
        command: [sh, -c]
        args:
          - poetry build
        workingDir: /src/{{workflow.parameters.path}}
        volumeMount:
          - name: workdir
            path: src/
    - name: push-package
      inputs:
        parameters:
          - name: registry
          - name: base-image
      container:
        image: "{{inputs.parameters.registry}}{{inputs.parameters.base-image}}"
        command: [sh, -c]
        args:
          - poetry publish -r private
        workingDir: /src/{{workflow.parameters.path}}
        volumeMount:
          - name: workdir
            path: src/
          
