apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-daemon-config
data:
  daemon.json: |
    {
      "insecure-registries": ["192.168.0.8:5000", "192.168.1.32:5000", "docker-registry.mw.local"],
      "experimental": true,
      "features": {
        "buildkit": true
      },
      "builder": {
        "network": "host"
      }
    }
