apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-daemon-config
data:
  daemon.json: |
    {
      "insecure-registries": ["docker-registry-service.docker-registry.svc.cluster.local:5000", "docker-registry.mw.local"],
      "experimental": true,
      "features": {
        "buildkit": true
      },
      "builder": {
        "network": "host"
      }
    }
