apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind-deployment
  labels:
    app: bind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind
  template:
    metadata:
      labels:
        app: bind
    spec:
      containers:
      - name: bind
        image: cytopia/bind
        volumeMounts:
        - name: bind-config
          mountPath: /etc/bind
          readOnly: true
        - name: bind-custom
          mountPath: /etc/bind/custom
      volumes:
      - name: bind-config
        configMap:
          name: bind-config
      - name: bind-custom
        emptyDir: {}