apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argo
  name: argo-svc-role-binding
subjects:
- kind: ServiceAccount
  name: argo-workflow-svc
  namespace: argo
roleRef:
  kind: Role
  name: argo-workflow-executor
  apiGroup: rbac.authorization.k8s.io
