apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        env:
          - name: KAFKA_KRAFT_MODE
            value: "true"
          - name: KAFKA_KRAFT_BROKER_ID
            valueFrom:
              fieldRef:
                fieldPath: index
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "false"
          - name: KAFKA_PORT
            value: "9092"
        ports:
        - containerPort: 9092
