apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        env:
          - name: KAFKA_MODE
            value: "kraft"
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "false"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          - name: KAFKA_CFG_NODE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
            value: "0"
          - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
            value: "PLAINTEXT"
        ports:
        - containerPort: 9092
