apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    app: kafka-service
spec:
  ports:
    - port: 80
      targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP
