apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    app: kafka-service
spec:
  clusterIP: None
  ports:
  - name: kafka
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
