apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo-workflow-ingress
  namespace: argo
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`argo-workflow.mw.local`) && PathPrefix(`/`)
    priority: 10
    services:
    - name: argo-workflow-server
      port: 2746

