apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo-config.yaml: |-
    storage:
      trace:
        backend: local
        local:
          path: /etc/tempo/data
