apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:latest
        ports:
        - containerPort: 3100
      volumeMounts:
        - name: tempo-volume
          mountPath: /etc/tempo
  volumes:
    - name: grafana-volume
      persistentVolumeClaim:
        claimName: grafana-pvc
