apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  labels:
    app: tempo-service
  namespace: monitoring
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3200
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    app: tempo
  type: ClusterIP
