apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  labels:
    app: tempo-service
  namespace: monitoring
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3200
  selector:
    app: tempo
  type: ClusterIP
